AllCops:
  RunRailsCops: true

  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Style/DotPosition:
  EnforcedStyle: trailing
  SupportedStyles:
    - leading
    - trailing
